#!/usr/bin/env bash

rm -rf build thirdparty

cmake -S . -B build \
-DCMAKE_C_COMPILER=gcc \
-DCMAKE_CXX_COMPILER=g++ \
-DCMAKE_BUILD_TYPE=Release \
-DSEAL_BUILD_EXAMPLES=OFF \
-DSEAL_BUILD_TESTS=ON \
-DSEAL_BUILD_BENCH=OFF \
-DSEAL_BUILD_DEPS=ON \
-DSEAL_USE_MSGSL=OFF \
-DSEAL_USE_ZLIB=OFF \
-DSEAL_USE_ZSTD=OFF \
-DBUILD_SHARED_LIBS=ON \
-DSEAL_USE_INTEL_HEXL=ON

cmake --build build -j
